### ISSUE TITLE
Utilisation de Github Pages

### ISSUE THREAD

**Issue by bourgeois** [nicbou/etsmtl#1]
Planifiez-vous utiliser GitHub Pages pour l'hébergement du site ?

Si oui, vous pourriez bouger les pages vers une branche `gh-pages`, comme [la doc indique](https://help.github.com/articles/user-organization-and-project-pages/#project-pages).

On pourra aussi ajouter un fichier CNAME éventuellement, lorsque quelqu'un aura un domaine personnalisé.

**Comment by nicbou** [comment]
S'ti d'bon plan

**Comment by bourgeois** [comment]
Si on est pour utiliser la branche `gh-pages`, est-ce que ce serait une bonne idée de supprimer la branche `master` et configurer le repo pour utiliser `gh-pages` par défaut ?

Ça éviterait probablement la confusion, parce là il y a deux branches avec le même code :(
