### ISSUE TITLE
Plateforme manquante

### ISSUE THREAD

**Issue by pric** [nicbou/etsmtl#2]
Ca manque un peu de contenu tout ça, je verrais bien une belle plateforme en Node.JS avec le framework express pour permettre de bien se lancer.

**Comment by nicbou** [comment]
Yep, bien d'accord. J'ai juste créé une petite base, mais ça serait bien d'avoir quelque chose de plus solide.

**Comment by bourgeois** [comment]
Avez-vous considéré une alternative client-side avec Angular/Ember/Backbone en complément d'un système backend du genre [Firebase](https://www.firebase.com) ou [Orchestrate](https://orchestrate.io) ? (Orchestrate fait partie du Github Student Pack en plus).

Ça pourrait complètement éviter d'avoir un backend à maintenir et d'avoir une app lightweight qui roule dans le browser. On avait utilisé ça pour le système de commentaires en GTI710. Ça fonctionnait bien. En bonus, tous les browsers se mettaient à jour realtime quand il y a du nouveau contenu (un peu comme Trello).

Aussi, ça coûterait un gros 0$ de hosting puisque vous pourriez garder Github Pages (qui est servi à travers un CDN et donc ultra rapide).

C'est juste une idée que je lance :)

**Comment by pric** [comment]
J'aime bien l'idée du Angular. On pourrait ainsi faire un backend complètement indépendant... Débatons sur la technologie!

**Comment by bourgeois** [comment]
Effectivement, ça permettrait d'offrir un API unique au lieu de générer les pages coté serveur. Ça simplifierait aussi de beaucoup les choses dans l'éventualité ou une application mobile verrait le jour (un seul API à maintenir pour tout).

Quant à la technologie, ça n'a peu d'importance. C'est de savoir si vous voulez écrire/maintenir du code back-end ou utiliser un DaaS (Database as a service) qui pourrait offrir les fonctionnalités de persistance.

**Comment by pric** [comment]
Je suis tout à fait en accord pour ce qui est de l'API pour les éventuelles extensions de nos services. Mais pour ce qui est du backend, je suis ouvert, quel est votre technologie de prédilection? Ce que j'aime du node c'est que c'est facile à déployer et à maintenir. Je verrais bien du python aussi!

**Comment by nicbou** [comment]
J'aime bien l'idée d'Angular + Orchestrate, mais sans trop savoir où on s'en va avec ça, j'irais avec quelque chose de plus conventionnel. On peut toujours mettre ça sur un instance gratuite de Heroku si on part ça en Node.js, Python et cie. Qu'est-ce que vous en pensez?

**Comment by pric** [comment]
Bah ce qui est bien c'est que si on utilise un backend en API on peut très facilement le mettre sur heroku de façon gratuite, et le frontend je présume qu'on peu le mettre sur gh-pages? Pis on va se le dire, Node c'est supérieur à tout. Donc on prends node :+1:

**Comment by bourgeois** [comment]
Ouais, c'est vrai qu'il y a toujours le free-tier de Heroku, j'avais oublié ça. Sinon, dans le pire des cas, on a tous 100$ de crédit Digital Ocean avec le Github Student Pack (on pourra spinner une VM si ça viens trop gros).

Pour le nom de domaine, je viens de voir que `etsmtl.io` n'est pas pris. Avec le rabais étudiant (Github Student Pack, encore une fois), ça coute seulement 25$ au lieu de 50$ chez Namecheap. Ça pourrait être à considérer.

**Comment by nicbou** [comment]
Bon, alors on se dit OK pour une API REST avec Node.js et un frontend Angular? Le free tier de Heroku + MongoLab devrait amplement faire la job.

Le domaine aurait de l'allure, mais je vais quand même essayer d'entrer en contact avec le gars de etsmtl.me. Qui sait?

**Comment by pric** [comment]
Makes a lot of sens to me! 

"Bon, alors on se dit OK pour une API REST avec Node.js et un frontend Angular? Le free tier de Heroku + MongoLab devrait amplement faire la job."

**Comment by bourgeois** [comment]
Bonne chance pour contacter la crisse d'air bête de etsmtl.me. Voici la dernière réponse que j'ai eu lorsque j'avais une question concernant le projet.

![](http://i.imgur.com/7kXR3ZR.png)

**Comment by nicbou** [comment]
![](http://www.reactiongifs.com/wp-content/uploads/2012/12/friday-damn.gif)

**Comment by frank8211** [comment]
Agréable le gars! 

Francis Provost<div>E: francis.provost@gmail.com</div><div>T: 514-796-3432</div>

Le lundi 19 janv. 2015 à 22:17, Nicolas Bouliane <notifications@github.com> a écrit :

![](http://www.reactiongifs.com/wp-content/uploads/2012/12/friday-damn.gif)

---

**Comment by pboutin** [comment]
Je sais pas si votre choix d'Angular est coulé dans le béton, perso je travaille avec EmberJS depuis plus d'un an sur un projet qui spin en prod at the moment. Si vous vouliez envisager ce choix là et que vous vous posiez des questions sur "comment on ferait tel ou tel truc", genez-vous pas !

**Comment by nicbou** [comment]
@pboutin, tu ferais mieux de mettre ça dans un nouveau ticket. Je ne suis pas contre de mon côté.

**Comment by pboutin** [comment]
@nicbou making it right meow

**Comment by dannytranlx** [comment]
Quel sont les besoins pour avoir une plateforme plus complexe qu'une simple page html static?

**Comment by Becojo** [comment]
@dannytranlx Entièrement d'accord. 

Il faudrait définir ce que doit offrir le site et choisir la technologie plus tard selon les besoins.

**Comment by bourgeois** [comment]
Il faudrait s'entendre sur quel dépôt de code utiliser, il a celui-ci et lussier/etsmtl.

Et je suis aussi d'avis qu'une simple page HTML statique serait plus que suffisant pour un site d'informations.

**Comment by dannytranlx** [comment]
Je crois que pour la notoriété du projet, on devrait rester avec le domaine/projet http://etsmtl.me. Le projet devrait être plus accessible maintenant. N'hésitez pas à collaborer!

**Comment by pboutin** [comment]
je renvoyais surtout la balle pour les vieux comments qui parlaient d'angular, nodejs, mongo et compagnie. Indeed, tant que ça reste juste un catalogue de bookmark, keep it simple
