### ISSUE TITLE
Proposition EmberJS

### ISSUE THREAD

**Issue by pboutin** [nicbou/etsmtl#6]
Comme mentionné dans un autre issue, j'ai présentement 1 an et demi d'expérience dans un projet solo EmberJS qui est en production présentement. Si vous vouliez encore considérer Ember je pourrais surement répondre à quelques questions à cet effet.

Les trucs cools d'Ember : 
- Drivé par la communauté et les entreprises pour des "real life" projects
- Plus proche du modèle MVC que l'on connait tous
- Jumelé à Qunit rend le truc hyper fastoche et *fun* testé
- Utilise Handlebars pour le templateting

Y'a sans doutes des trucs vraiment nice du côté d'Angular mais je veux pas parler au travers mon chapeau, je l'ai jamais testé moi-même

> Angular, in my opinion, is much more of a research project than Ember.js. Just look at the terminology: Ember talks about models, views, and controllers. Angular's guide requires you to learn about things like scopes, directives and transclusion.

> - http://www.quora.com/Client-side-MVC/Is-Angular-js-or-Ember-js-the-better-choice-for-JavaScript-frameworks

**Comment by Becojo** [comment]
On pourrait aussi virer ça en flame war sur quel framework JS choisir considérant la quantité disponibles de nos jours...

À moins qu'il soit prévu que le front-end du projet devienne très complexe, je vois vraiment pas l'utilité d'ajouté un gros framework tel que Ember ou Angular.

**Comment by nicbou** [comment]
+1. J'ai ouvert un issue sur l'idée de merger avec le repo officiel d'etsmtl.me, maintenant que Danny en a le contrôle. Si c'est le cas, on oublie le backend.

**Comment by pboutin** [comment]
Si jamais l'idée de faire plus qu'un bookmark page revient sur la table ou si vous avez des questions sur le sujet, n'hésitez pas à me poker !
